version: "3.8"
services:
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
      # Gemのキャッシュ用 (任意)
      # - gem_cache:/usr/local/bundle/gems
    ports:
      - "3000:3000"
    depends_on:
      - db # データベースサービスを利用する場合
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgresql://postgres:password@db:5432/rails-mcp-sample-app_development

  db: # PostgreSQLの例
    image: postgres:15 # 必要に応じてバージョンを変更
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  # gem_cache: # Gemキャッシュ用 (任意)
